chores: Update build.yml
critique-digitale/critique-digitale.ch pull request #6
Opened 2023-08-03 14:23 UTC by maehr

# Pull request

## Proposed changes

This pull request proposes the upgrade of SvelteKit to version 1.0. The latest version brings a myriad of improvements and bug fixes that will greatly improve our current development process. This version has been well tested and is considered stable for production environments.

Please see the [SvelteKit 1.0 release notes](https://svelte.dev/blog/announcing-sveltekit-1.0) for detailed information on what this upgrade offers.

## Types of changes

This code introduces the following type of change: 

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [x] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-08-07 19:51 UTC, flicksolutions requested changes
Everything looks really fine! The things I found are minor.

2023-08-07 19:51 UTC, flicksolutions commented on .prettierrc
> +	"pluginSearchDirs": ["."],
Ich schlage vor, prettier auf die nächste Major-version upzudaten.
Ab 3.0 wurde pluginSearchDirs dann entfernt: https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker

2023-08-07 19:51 UTC, flicksolutions commented on package.json
> +		"prettier": "^2.8.0",
I propose ^3.0.1
following prettier-plugin-svelte and eslint-config-prettier have to be updated aswell.

2023-08-07 19:51 UTC, flicksolutions commented on playwright.config.js
Can't say much about playwright... I've never used it.
I just assume this is right.

2023-08-07 19:51 UTC, flicksolutions commented on src/routes/onboarding/+page.svelte
> +	import About from '../../lib/components/About.svelte';
```suggestion
	import About from '$lib/components/About.svelte';
```

2023-08-07 19:51 UTC, flicksolutions commented on src/routes/onboarding/+page.svelte
> +	import Videos from '../../lib/components/Videos.svelte';
dito

2023-08-07 19:51 UTC, flicksolutions commented on src/routes/onboarding/+page.svelte
`/videos/speakers.png` is linked on line 50. this file doesn't exist. I propose to rename `/videos/speaker.png` to `/videos/speakers.png`

2023-08-07 20:51 UTC, maehr commented on mdsvex.config.js
> +	smartypants: {
Duplication removed

2023-08-07 20:51 UTC, maehr commented on svelte.config.js
> +import adapter from '@sveltejs/adapter-auto';
Auto also works for cloudflare (if I am not mistaken)

2023-08-07 20:59 UTC, maehr commented on mdsvex.config.js
> +	smartypants: {
removed

2023-08-08 18:21 UTC, flicksolutions approved these changes
approved! Well done!

2023-08-09 06:34 UTC, merged