feat: change adapter to static&update dependencies
critique-digitale/critique-digitale.ch pull request #7
Opened 2023-08-12 11:53 UTC by maehr

# Pull request

## Proposed changes

Change adapter to static to render all pages statically.

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-08-12 12:39 UTC, maehr commented
The build works, the settings changed due to the switch of the adapter: https://static-site.critique-digitale-ch.pages.dev/

2023-08-12 15:39 UTC, flicksolutions commented
One general question:
Right now if you preview the build with `npm run build` you will not see the optimized version, because vite somehow builds from _.svelte-kit/output/_ I tried adding ` && jampack .\\.svelte-kit\\output` (windows-specific path just for tests) but then jampack doesn't find the images in the html (because they're in the client folder) and raises issues...
There are three options here:
1. I investigate further and see wether I can get vite to preview from the build folder directly (should work for static pages)
2. live with the errors that jampack generates until a _silent_ option is available
3. live with your preview not being optimized...

How should I proceed?

2023-08-12 17:29 UTC, maehr commented
The optimization works just fine. You have to run `npm run postbuild` as well (which is done automatically by Cloudflare Pages). The adapter static outputs to the folder `build`. I adjusted `package.json` accordingly.

2023-08-12 20:11 UTC, flicksolutions requested changes
The hiding of the controls doesn't work as proposed. With line 55 deleted, it works.
The proposed changes in package.json are only for DX.

2023-08-12 20:11 UTC, flicksolutions commented on src/lib/components/Videos.svelte
> +	$: clearTimeout(showControlsTimeout);
this only works for me, if I delete this line... but without the line it works fine...

```suggestion
	
```

2023-08-12 20:11 UTC, flicksolutions commented on src/lib/components/Videos.svelte
> +	$: clearTimeout(showControlsTimeout);
also: add `cursor: pointer;` on line 95.

2023-08-14 08:02 UTC, maehr commented
@flicksolutions I introduced some bugs, please give me one more day before reviewing. Sorry

2023-08-14 10:03 UTC, maehr commented
> @flicksolutions I introduced some bugs, please give me one more day before reviewing. Sorry

@flicksolutions done! I hope I fixed all requested issues.

2023-08-22 17:44 UTC, merged